# Generated by Django 6.0.6 on 2026-06-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KoboConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_url', models.URLField(default='https://kobo.ifrc.org')),
                ('api_token', models.CharField(blank=True, max_length=255)),
                ('cache_ttl_seconds', models.PositiveIntegerField(default=300, help_text='How long to cache API responses (seconds). 300 = 5 minutes.')),
            ],
            options={
                'verbose_name': 'KoboToolBox Configuration',
                'verbose_name_plural': 'KoboToolBox Configuration',
            },
        ),
    ]
