# Generated by Django 6.0.6 on 2026-06-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='koboconfig',
            name='selected_form_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='koboconfig',
            name='selected_form_uid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
