# Generated by Django 6.0.6 on 2026-06-14 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0003_configuredform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='koboconfig',
            name='brand_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='koboconfig',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='koboconfig',
            name='org_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='DashboardGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('admins', models.ManyToManyField(blank=True, related_name='administered_groups', to=settings.AUTH_USER_MODEL)),
                ('forms', models.ManyToManyField(blank=True, related_name='groups', to='kobo.configuredform')),
                ('members', models.ManyToManyField(blank=True, related_name='dashboard_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
