# Generated by Django 6.0.6 on 2026-06-16 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0004_koboconfig_brand_color_koboconfig_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('config', models.JSONField(default=dict)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_configs', to='kobo.configuredform')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
