# Generated by Django 6.0.6 on 2026-06-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_power_user',
            field=models.BooleanField(default=False),
        ),
    ]
